static inline u32 armv7_pmnc_read(void);
static inline void armv7_pmnc_write(u32 val);
static inline int armv7_pmnc_has_overflowed(u32 pmnc);
static inline int armv7_pmnc_counter_valid(struct arm_pmu *cpu_pmu, int idx);
static inline int armv7_pmnc_counter_has_overflowed(u32 pmnc, int idx);
static inline void armv7_pmnc_select_counter(int idx);
static inline u64 armv7pmu_read_counter(struct perf_event *event);
static inline void armv7pmu_write_counter(struct perf_event *event, u64 value);
static inline void armv7_pmnc_write_evtsel(int idx, u32 val);
static inline void armv7_pmnc_enable_counter(int idx);
static inline void armv7_pmnc_disable_counter(int idx);
static inline void armv7_pmnc_enable_intens(int idx);
static inline void armv7_pmnc_disable_intens(int idx);
static inline u32 armv7_pmnc_getreset_flags(void);
static void armv7_pmnc_dump_regs(struct arm_pmu *cpu_pmu);
static void armv7pmu_enable_event(struct perf_event *event);
static void armv7pmu_disable_event(struct perf_event *event);
static irqreturn_t armv7pmu_handle_irq(struct arm_pmu *cpu_pmu);
static void armv7pmu_start(struct arm_pmu *cpu_pmu);
static void armv7pmu_stop(struct arm_pmu *cpu_pmu);
static int armv7pmu_get_event_idx(struct pmu_hw_events *cpuc, struct perf_event *event);
static void armv7pmu_clear_event_idx(struct pmu_hw_events *cpuc, struct perf_event *event);
static int armv7pmu_set_event_filter(struct hw_perf_event *event, struct perf_event_attr *attr);
static void armv7pmu_reset(void *info);
static int armv7_a8_map_event(struct perf_event *event);
static int armv7_a9_map_event(struct perf_event *event);
static int armv7_a5_map_event(struct perf_event *event);
static int armv7_a15_map_event(struct perf_event *event);
static int armv7_a7_map_event(struct perf_event *event);
static int armv7_a12_map_event(struct perf_event *event);
static void armv7pmu_init(struct arm_pmu *cpu_pmu);
static void armv7_read_num_pmnc_events(void *info);
static int armv7_probe_num_events(struct arm_pmu *arm_pmu);
static int armv7_a8_pmu_init(struct arm_pmu *cpu_pmu);
static int armv7_a9_pmu_init(struct arm_pmu *cpu_pmu);
static int armv7_a5_pmu_init(struct arm_pmu *cpu_pmu);
static int armv7_a15_pmu_init(struct arm_pmu *cpu_pmu);
static int armv7_a7_pmu_init(struct arm_pmu *cpu_pmu);
static int armv7_a12_pmu_init(struct arm_pmu *cpu_pmu);
static int armv7_a17_pmu_init(struct arm_pmu *cpu_pmu);
static u32 venum_read_pmresr(void);
static void venum_write_pmresr(u32 val);
static void venum_pre_pmresr(u32 *venum_orig_val, u32 *fp_orig_val);
static void venum_post_pmresr(u32 venum_orig_val, u32 fp_orig_val);
static u32 clear_pmresrn_group(u32 val, int group);
static int armv7_pmu_device_probe(struct platform_device *pdev);